apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery-container
        image: x03xd/amazon_clone:v0.5api
        ports:
          - containerPort: 8100
        command: ["celery", "-A", "amazon", "worker", "--loglevel=info"]
        env:
        #- name: CELERY_BROKER_HOST
        #  valueFrom:
        #    configMapKeyRef:
        #      name: configmap
        #      key: amqp-host
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: celery-result-backend
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: django_settings_module
---
apiVersion: v1
kind: Service
metadata:
  name: beat-service
spec:
  selector:
    app: beat
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
