apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery-container
        image: x03xd/amazon_clone:v0.2api
        ports:
          - containerPort: 8100
        command: ["sh", "-c"]
        args:
          - "celery -A worker beat loglevel=info && celery -A amazon beat loglevel=info"
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: amqp-host
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: celery-result-backend
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: django_settings_module

---
apiVersion: v1
kind: Service
metadata:
  name: beat-service
spec:
  selector:
    app: beat
  ports:
    - protocol: TCP
      port: 3400
      targetPort: 8100