apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: x03xd/amazon_clone:v2.0ui
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: env-config
          mountPath: /app
      volumes:
      - name: env-config
        configMap:
          name: frontend-configmap
          items:
          - key: app.env
            path: .env
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30005
      targetPort: 3000
