apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  appConfig.js: |
 var appConfig = {
  FRONTEND_HOST: "example.local:TEST",
  BACKEND_HOST: "example.local:TEST/api",
  PROTOCOL: "http",
 };