apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  #backend
  secret-key: OGZhJWdrdGMz
  fixer-api-key: M2YxZDhjMTdhODA1OTZkNWE4OWJhMDAwMWY4ZmEyYTU=
  stripe-secret-key: c2tfdGVzdF81MU5seG9YTEl0YXB6bFlSTkhQOXlxVGNzYWdGNzZVYnZpSlU2ZVZZaWRIbUJveHBnN1BtbTFvVldVMklqRzAyZ3JuR2xjZERsWVFkNmdZN1lQVFBGWHZuYjAwYnBOVXpqd2w=
  stripe-endpoint-secret: d2hzZWNfODBlODlkN2IzZjAyMWExMzIwZDA1NzZjNzA5OTJjMDI2MGRlM2Y4ZTdkZDNlMzAyYzE0OTQzZGMyMzc3ZDIwNg==

  #rabbitmq
  rabbitmq-default-user: Z3Vlc3Q=
  rabbitmq-default-pass: Z3Vlc3Q=

  #postgres
  postgres-db: bmV3X2FtYXpvbg==
  postgres-user: cG9zdGdyZXM=
  postgres-password: YWRtaW4=
